### PR TITLE
FIX: Generated shebang with path to python invalid if path contains spaces 

### LINKED ISSUE #2271: Generated shebang with path to `python` invalid if path contains spaces
Creating a venv in a path with a space causes running a process in a new terminal to fail.
```sh
$ mkdir /tmp/with\ space
$ cd /tmp/with\ space
$ python -m venv venv
$ source venv/bin/activate
$ pip install pwntools
$ python pwntools/examples/attach.py
```

Results in generating something like this
```
    #!/tmp/with space/venv/bin/python
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', '/bin/bash', '8902', '-x', '/tmp/pwnrqobb6w5.gdb'], os.environ)
```

With the shell complaining
```
bash: /tmp/tmpihzr5hsv: /tmp/with: bad interpreter: No such file or directory
```

### PR DESCRIPTION
**Pull request by ksshen0000**
# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

### CODE REVIEW

**Comment by peace-maker** [comment]
This seems to assume Python 3 which might not be installed when using Python 2.

**Comment by ksshen0000** [comment]
there is another option that is to create a softlink. But the website says python2 is deprecated

**Comment by peace-maker** [comment]
We're still supporting python 2 installs right now though, so need to think of that.

Another way would be to ignore the shebang line and just add the `sys.executable` to the `argv` array directly.

**Review by Arusekk — APPROVED** [review]
Honestly I think it is okay to just always use python3; this is just a thin wrapper, so nothing bad should happen.

**Comment by peace-maker** [comment]
I think your `/usr/bin/env /path/with spaces/python` suggestion is better, since it is fully backwards compatible. And I agree it should only be emitted if there are spaces in the `sys.executable` path.
https://github.com/Gallopsled/pwntools/issues/2271#issuecomment-1762728840

**Pull request merged**
