### PR TITLE
Fix continuous integration tests

### PR DESCRIPTION
**Pull request by heapcrash**
This Pull Request is for fixing continuous integration testing for Pwntools

### CODE REVIEW

**Comment by Arusekk** [comment]
I would seriously start from #1754, but it turns out that on newer ubuntu gdb tests hang indefinitely (at least on Travis, because on GHA it had been all right).

**Comment by Arusekk** [comment]
The problem on GHA py3 is that somehow sphinx tests irrelevant module members in irrelevant modules (like `for arch in CAT_PROC_MAPS_EXIT` being run both where it should (elf.elf) and where it should not [in libcdb, and in rop.rop and in runner]).

You can see it yourself in the logs.
Is it some strange sphinx version? Maybe we could pin it?

**Comment by peace-maker** [comment]
The libcdb tests are temporarily broken due to https://libc.rip/ having trouble. That tested libc version usually is available if the server wouldn't 500 out, so I'd keep the tests in.

**Comment by heapcrash** [comment]
@peace-maker We can't have our CI pipeline reliant on an unreliable external source

**Comment by Arusekk** [comment]
This still does not explain why GHA+py3 == test cases run multiple times...

**Comment by heapcrash** [comment]
> This still does not explain why GHA+py3 == test cases run multiple times...

I think this is fixed now, right?

**Comment by Arusekk** [comment]
I guess it is

**Comment by heapcrash** [comment]
I think we can close this @Arusekk since other changes have made CI tests successful.

Please close this issue if you agree.

**Pull request closed without merging**
