### PR TITLE
Various enhancements to ELF

### PR DESCRIPTION
**Pull request by zachriggle**
- Better documentation
- Remove generally unused fields of checksec
- Better support for uncommon architectures
- Add a few fields e.g. `bits` and `endian`

### CODE REVIEW

**Comment by RobertLarsen** [comment]
argh...that was not what I wanted

**Comment by RobertLarsen** [comment]
Well, actually now it is.
I had something failing, but that was me trying to be too clever...this is fine.

**Comment by zachriggle** [comment]
Wait so did this get merged?

**Comment by RobertLarsen** [comment]
Yes. Sorry 'bout this.
I saw a problem and would reply, but instead I merged (due to a known bug in my firmware that triggers when I haven't had enough sleep). Then noticed that there was no problem.

**Pull request merged**
