### PR TITLE
Update Timeout semantics

### PR DESCRIPTION
**Pull request by zachriggle**
Use None to imply "never", and to use a sentinel object for default timeouts

Addresses #251

This again has a big performance hit, so I'll defer to @br0ns for recommendations.  I assume that it's the use of sentinel objects that are looked up rather than constants

### CODE REVIEW

**Comment by br0ns** [comment]
I think we should merge this now and do the cleanup in another PR.

**Comment by br0ns** [comment]
BTW, @zachriggle, did you have a look at https://github.com/Gallopsled/pwntools/tree/timeout-None-forever?

**Comment by zachriggle** [comment]
Looking now.  I'll open a new PR.

**Comment by zachriggle** [comment]
Merged with @br0ns' additions

**Pull request merged**
