### PR TITLE
Fix config types for integer values

### PR DESCRIPTION
**Pull request by zachriggle**
Fixes Gallopsled/pwntools#988

### CODE REVIEW

**Comment by zachriggle** [comment]
CI passes, coverage went down presumably because of Android stuff.  In any case, this fixes my stuff locally.  Can you verify, @Idolf?

I'm not sure how to add tests for this in a useful manner.

**Comment by TethysSvensson** [comment]
Verified.

**Comment by TethysSvensson** [comment]
Should I do a new release with this?

**Comment by zachriggle** [comment]
Sure :)

**Pull request merged**
