### PR TITLE
Fix documentation generation since autoprogram broke Python2

### PR DESCRIPTION
**Pull request by zachriggle**
Fixes Gallopsled/pwntools#776

### CODE REVIEW

**Comment by zachriggle** [comment]
Before:

```
$ make html
...
reading sources... [ 10%] commandline
Exception occurred:
  File "/Users/riggle/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sphinxcontrib/autoprogram.py", line 223, in make_rst
    yield textwrap.indent(usage, '    ')
AttributeError: 'module' object has no attribute 'indent'
The full traceback has been saved in /var/folders/hv/wnvzfp2d73b8cdxj7w_98tv0008rd2/T/sphinx-err-DMGled.log, if you want to report the issue to the developers.
```

After:

```
$ make html
...
build succeeded, 52 warnings.
```

**Comment by zachriggle** [comment]
Assigned to @Idolf since this needs to be backported to `stable` for docs generation to work.  Doesn't need a new release.

Targeted `stable` so that we can just forward-merge.

**Comment by TethysSvensson** [comment]
This has been cherry-picked.

**Comment by zachriggle** [comment]
This also needs to be forward-merged to beta/dev

**Comment by TethysSvensson** [comment]
It already has.

**Comment by zachriggle** [comment]
Thanks! <3

**Pull request closed without merging**
