### PR TITLE
[elf.py] convert linux string banner into an actual str

### PR DESCRIPTION
**Pull request by lucasg**
``self.string(address)`` actually return a bytes object containing the raw bytes, not a string in a pythonesque sense !
Since quite some time on Python3, ``re.search`` only works on proper str so we need to convert it before feeding it to ``re.search``

``.decode()`` works both on Python2 and Python3

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

### CODE REVIEW

**Comment by lucasg** [comment]
Note: this bug also affects the ``stable`` branch

**Comment by Arusekk** [comment]
Please run on your branch:
```sh
git rebase dev --onto stable
git push
```
and then change the branch to `stable` on GH by clicking on the Edit button next to PR title. It should go fine.

**Comment by lucasg** [comment]
done, this should run against the stable branch

**Comment by zachriggle** [comment]
TIL `git rebase foo --onto bar`.  Thanks for this, @Arusekk!  I've always just created a new branch off e.g. `stable` and manually cherry-picked each commit.

**Pull request merged**
