### PR TITLE
Memleak can now leak whole structures

### PR DESCRIPTION
**Pull request by kokjo**

### CODE REVIEW

**Comment by zachriggle** [comment]
Did you re-implement this? I think I've written code like this before or I'm having déjà Vu hahaha

**Comment by zachriggle** [comment]
Ah never mind I was thinking of the "field" code right underneath it. Cool! :-)

**Comment by kokjo** [comment]
well the documentation of the .field was wrong, so i implemented it the "entire structure" part in its own function. :)

**Comment by zachriggle** [comment]
Looks like you removed the description of the function from the docstring on "def field".  Would you mind re-adding / updating it so that it's more accurate? Thanks :D

**Pull request merged**
