### PR TITLE
Fix timeout not working for functions using recvpred.

### PR DESCRIPTION
**Pull request by peter50216**
For example, recvregex.

Also delete some useless code.

### CODE REVIEW

**Comment by peter50216** [comment]
Don't know why travis test fail... It does pass in my VM, and the error doesn't seems to be relevant to the changed code. Could someone rerun the travis test please?

**Comment by peter50216** [comment]
Accidentally deleted the commit on github :(. Reopened.

**Comment by Idolf** [comment]
@zachriggle: Is this still relevant after #636?

**Comment by zachriggle** [comment]
The reporter did not provide a test case which failed, only some code changes which now cause merge conflicts.

Everything looks like it works for me, after #636.

```
>>> r=remote('google.com', 80, timeout=3)
[x] Opening connection to google.com on port 80
[x] Opening connection to google.com on port 80: Trying 2a00:1450:4009:808::200e
[+] Opening connection to google.com on port 80: Done
>>> r.recvregex('foobar')
''
```

**Pull request closed without merging**
