### PR TITLE
Add Python 3 to tesing in allow_failures mode

### PR DESCRIPTION
**Pull request by cclauss**
Also add flake8 tests because it finds 52 undefined names in Python 2.
* https://travis-ci.org/Gallopsled/pwntools/jobs/321619761#L757

# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

### CODE REVIEW

**Comment by zachriggle** [comment]
Python3 isn't supported, I'm not sure why we'd add this

**Comment by cclauss** [comment]
There are 52 issues on Python 2.

**Comment by zachriggle** [comment]
Cool, thanks for pointing that out.

At a quick glance, most of these are due to dynamic injection of methods, or code which is only run under Sphinx, after `from pwn import *` (which adds lots of things to the global namespace).

In any case, this can't be merged until the CI passes with this enabled.  Please:

1. Remove the Python3 testing section.
2. Resolve the issues discovered by this change

Thanks!

**Comment by cclauss** [comment]
Python 3 tests are [run in __allow_failures__ mode](https://github.com/Gallopsled/pwntools/pull/1086/files#diff-354f30a63fb0907d4ad57269548329e3R26)...  They always pass.

**Comment by zachriggle** [comment]
# Python2 Tests

The Python2 tests are failing, see the Travis CI status.  You need to fix those issues before we can accept this pull request.

# Python3 Tests

This adds to the amount of time it takes for the CI tests to run, since we cannot run them in parallel.  I won't accept this change, particularly since the project does not support Python3.

**Comment by zachriggle** [comment]
This is no longer needed, see the `dev3` branch

**Comment by cclauss** [comment]
Current stats on the __dev3__ branch are:
```
Python:
13    E999 SyntaxError: invalid syntax
53    F821 undefined name 'tags'
9     F822 undefined name 'LlvmLexer' in __all__
75

Legacy Python:
49    F821 undefined name 'tags'
9     F822 undefined name 'LlvmLexer' in __all__
58
```

**Pull request closed without merging**
