### PR TITLE
python3 - 2to3

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
# Pwntools Pull Request

This is experimental p3 support, works for me so far. Not complete.

### CODE REVIEW

**Comment by ghost** [comment]
@h4ck3rm1k3 why do you want pwntools to change to Python 3?

**Comment by ghost** [comment]
@h4ck3rm1k3 and all tests will fail because you didn't changed travis to python 3

**Comment by h4ck3rm1k3** [comment]
I want to use python3 because it is the future. I will work on this more.

**Comment by ghost** [comment]
@h4ck3rm1k3 but don't immediatly create a pull request, lol

**Comment by h4ck3rm1k3** [comment]
I would like to use the build system, dont expect to merge any time soon. can you create a p3k branch to merge to ?

**Comment by ghost** [comment]
@h4ck3rm1k3 I'm not a dev and not a contributor, just a user

**Comment by zachriggle** [comment]
This is on the radar, but we'd truly prefer it is if it is bi-compatible
with Py2 and Py3. See the tracking bugs for design recommendations.

**Comment by h4ck3rm1k3** [comment]
@zachriggle I understand, have seen it working before for other projects, but can we at least create a branch for the v3 to get it working and then merge it back on step 2?

**Comment by zachriggle** [comment]
I have a branch\* on V3 which works and passes all of the tests on V3, see
the tracking bugs.

*From a year ago

**Comment by zachriggle** [comment]
*on V2 and V3

**Comment by h4ck3rm1k3** [comment]
oh, ok

**Comment by h4ck3rm1k3** [comment]
you mean #529

**Comment by h4ck3rm1k3** [comment]
and this branch https://github.com/arthaud/python3-pwntools

**Comment by zachriggle** [comment]
Nope, I meant this branch

https://github.com/binjitsu/binjitsu/tree/futurized

**Pull request closed without merging**
