### PR TITLE
#1494 ROP representation with short chars

### PR DESCRIPTION
**Pull request by layderv**
# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

This commit fixes the behavior of ROP when `build()`ing with strings.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

### CODE REVIEW

**Comment by layderv** [comment]
Test:

```
from pwn import *
r = ROP([])
r.raw('a')
r.raw('b')
print(r.dump())
print(hexdump(str(r)))
```
Similar to the [one](https://github.com/Gallopsled/pwntools/issues/1494) zachriggle gave.

**Comment by layderv** [comment]
From:
```
        >>> rop = ROP([])
        >>> rop.raw('AAAAAAAA')
        >>> rop.raw('BBBBBBBB')
        >>> rop.raw('CCCCCCCC')
        >>> print(rop.dump())
```
Do we still expect:

```
        0x0000:          b'AAAA' 'AAAAAAAA'
        0x0004:          b'AAAA'
        0x0008:          b'BBBB' 'BBBBBBBB'
        0x000c:          b'BBBB'
        0x0010:          b'CCCC' 'CCCCCCCC'
        0x0014:          b'CCCC'
```
Or

```
        0x0000:          'AAAA' 'AAAAAAAA'
        0x0004:          'AAAA'
        0x0008:          'BBBB' 'BBBBBBBB'
        0x000c:          'BBBB'
        0x0010:          'CCCC' 'CCCCCCCC'
        0x0014:          'CCCC'
```

**Comment by layderv** [comment]
Can this be merged? Should I make some changes?

**Comment by Arusekk** [comment]
I will take a look at this PR in a couple days.

**Comment by Arusekk** [comment]
So this is just about the `generatePadding` thing? Just curious, was this line used in some useful context?

I don't quite like the idea of being able to seamlessly get binary data in the form of a string. Say we got some non-ascii bytes in the ROP chain. What do we get? And is it safe to convert it back to bytes, and what encoding should be used?

Like here (I did not test, I just point out the *not obvious* part of `__str__` semantics here):
```py
from pwn import *
r = ROP([])
r.raw(255)
r.raw('aaa') # whatever this means
             # (typed languages be like "TypeError: why the heck are you feeding TEXT to a uint8 array?"),
             # but let's assume this means the same as b'aaa'
print(r.dump())
print(hexdump(r.chain())) # meaningful
print(hexdump(bytes(r)))  # meaningful too, but less explicit
print(hexdump(str(r))) # eh? (does it give the same output at least?)
```

Just a loose thought, maybe the README should contain some alike basic explanation why str is not bytes and bytes is not str, and why this is not as nonsense as [some think](https://github.com/zardus/fuckpy3).

**Comment by layderv** [comment]
Thanks for the review.

> So this is just about the generatePadding thing? Just curious, was this line used in some useful context?

I had your same question and I couldn't find any use for that in this context.

> print(hexdump(str(r))) # eh? (does it give the same output at least?)

Indeed this breaks. To your point, should I raise an error instead of returning some string?

**Comment by Arusekk** [comment]
You see, this is quite complex, since python 2 bytes() uses __str__, and python 3 bytes() uses __bytes__.

I read that there is some class decorator called six.python2_unicode_compatible (I like the way it does nothing in python 3, and does simple patching in python 2). We could probably make something the other way round: python2_bytes_compatible, to ensure that in python 2 we set __str__ to __bytes__, and probably to nothing in python 3 (it would default to falling back on __repr__, yielding something similar to <SomeClass object at 0x7ff01337>). Well, for now I think you can just do __str__ = __bytes__ at class level, like spme other modules do. I will then code up some decorator like I mentioned and amploy it across pwntools. If you also want to help do this, please do.

**Comment by layderv** [comment]
Sounds good. I've pushed the fix as you suggested. I'll work on the decorator you mentioned as soon as this is merged.
Thank you for helping with this!

**Pull request merged**
