### PR TITLE
Changed `util.fiddling.hexdump_iter` to take a file object instead of…

### PR DESCRIPTION
**Pull request by br0ns**
… a string.  This massively speeds up `phd <file> | less` for huge files.

### CODE REVIEW

**Comment by zachriggle** [comment]
I think that @Idolf doesn't want any extra branches.  In the future, create the PR from a fork.

For the purpose of back-ports, does this have any functional changes? Or can it just be rolled into the "next release"?

**Comment by zachriggle** [comment]
Since this is against `dev` I'm just merging this myself :)

**Comment by br0ns** [comment]
@zachriggle, OK, I'll do PR's from a fork in the future.  Thanks for merging.

**Comment by TethysSvensson** [comment]
I am backporting this to stable now, as this is a regression fix.

**Comment by zachriggle** [comment]
This was cherry-picked to 3.0.2 so realistically that's the milestone

**Pull request merged**
