### PR TITLE
Have travis do an editable installation.  This is how we actually use it...

### PR DESCRIPTION
**Pull request by zachriggle**
..., so this is what should work.

### CODE REVIEW

**Comment by IdolfHatler** [comment]
Well, actually both should work in my opinion.

**Comment by zachriggle** [comment]
Agreed, both should work.  The only difference AFAIK is that this creates a symlink instead of copying the files.

**Comment by IdolfHatler** [comment]
I'm not sure I see the advantage of testing this instead of the correct install. If something breaks with the . install, we would notice, right?

(And it is not just symlinks, try looking in one of the files)

**Comment by IdolfHatler** [comment]
I can merge if you want, I just don't see any advantages (or disadvantages) to this.

**Comment by zachriggle** [comment]
True, it's not an actual symlink.  The path is simply added in `easy_install.pth` and a `pwntools.egg-link` file is added.

One small advantage is that we can tell people who want to work on pwntools to just `source .travis_install.sh` rather than extra instructions (if on Ubuntu).  This file might be renamed to make it more visible to developers.

#### pip install -e . or python setup.py develop

```
ls -la lib/python2.7/site-packages/pwn*
-rw-rw-r-- 1 user user 21 Jan  4 16:17 lib/python2.7/site-packages/pwntools.egg-link
```

#### pip install .

```
ls -lad lib/python2.7/site-packages/pwn*
drwxrwxr-x  2 user user 4096 Jan  4 16:20 lib/python2.7/site-packages/pwn
drwxrwxr-x 12 user user 4096 Jan  4 16:20 lib/python2.7/site-packages/pwnlib
drwxrwxr-x  2 user user 4096 Jan  4 16:20 lib/python2.7/site-packages/pwntools-2.2-py2.7.egg-info
```

**Pull request merged**
