### PR TITLE
Test corefiles manually during setup

### PR DESCRIPTION
**Pull request by heapcrash**
This should help to diagnose why CI fails during corefile generation.

### CODE REVIEW

**Comment by Arusekk** [comment]
This looks like the filter is piping through apport: the test would need to fetch the core file back from apport, like in the code.

**Comment by heapcrash** [comment]
It looks like we will have to rely on Travis CI to do any testing of the `Corefile` functionality since Github Actions dies immediately.

@Arusekk do you want to create a PR that disables Corefile tests for GHA?

**Comment by Arusekk** [comment]
They are already disabled, and I think this is no good, since they work fine inside pwntools. They just get kidnapped by systemd, but corefile handles it automagically.
I would rewrite the test as something like:
```sh
python -c 'from pwn import *; p = process(["sh", "-c", "kill -TRAP $$"]); p.recvall(); print(p.corefile.signal)'
```

**Comment by zachriggle** [comment]
We look up corefiles from systemd / apport already, the issue is that GHA
kills the whole thing if any child has a fatal signal.  We can disable this
functionality, but it breaks other things

*Zach Riggle*

**Comment by heapcrash** [comment]
New PR for this is #1596

**Pull request closed without merging**
