### PR TITLE
Use https instead of http wherever possible.

### PR DESCRIPTION
**Pull request by IdolfHatler**
Note that this means that I changed a few of the links from 
http://docs.pwntools.com to https://pwntools.readthedocs.org as we do not
currently have https on pwntools.com

### CODE REVIEW

**Comment by IdolfHatler** [comment]
@zachriggle I didn't know about docs.pwntools.org before today. I think we should promote it more, but first I think we should get https for it.

**Comment by zachriggle** [comment]
While we're at it, is there any opposition to changing all `/2.1.3` links to `/latest`?

**Comment by kristoff3r** [comment]
@IdolfHatler: just to avoid confusion, you probably meant docs.pwntools.com :P

**Comment by IdolfHatler** [comment]
@kristoff3r Changed my comments to reflect the reality.

**Pull request merged**
