### PR TITLE
Switch Travis-related Testing Infrastructure to Trusty

### PR DESCRIPTION
**Pull request by zachriggle**
[As of Sept 5th](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status), Travis CI has:

- Switched all builds to Ubuntu Trusty by default
- Deprecated `sudo: false` builds for Ubuntu Precise builds

Our tests don't work anymore because of this, see #1021.

### CODE REVIEW

**Comment by TethysSvensson** [comment]
What is the status on this?

**Comment by zachriggle** [comment]
:( <-- status


*Zach Riggle*

**Comment by Arusekk** [comment]
Is it possible to finally switch to new ubuntu version? Travis-ci says that `precise` is too old to test software on.

**Comment by zachriggle** [comment]
We've since moved to `xenial` so we can kill this

**Pull request closed without merging**
