### PR TITLE
Add support to retrieve the memory maps and heap structures

### PR DESCRIPTION
**Pull request by zer1t0**
Added a method `maps` in class `process`, which returns the list of memory maps of the process with all the details in `/proc/<pid>/maps`. In order to parse and store the information of `/proc/<pid>/maps`, 2 new classes were included in `pwnlib.util.proc`: `MemoryMap` and `MemoryMapFlags`.

The functionality of `ELF.maps` was not changed to avoid breaking compatibility, however it could be modified to add the full information of the maps.

An example of the use of this new method:
```
>>> from pwn import *
>>> p = process('/bin/sh')
[x] Starting local process '/bin/sh'
[+] Starting local process '/bin/sh': pid 6676
>>> for map in p.maps():
...     print(map)
... 
55662876c000-556628770000 r--p 00000000 fe:01 9832286           /usr/bin/dash
556628770000-556628782000 r-xp 00004000 fe:01 9832286           /usr/bin/dash
556628782000-556628788000 r--p 00016000 fe:01 9832286           /usr/bin/dash
556628788000-55662878a000 r--p 0001b000 fe:01 9832286           /usr/bin/dash
55662878a000-55662878b000 rw-p 0001d000 fe:01 9832286           /usr/bin/dash
55662878b000-55662878d000 rw-p 00000000 00:00 0
55662968f000-5566296b0000 rw-p 00000000 00:00 0         [heap]
7f33ab50d000-7f33ab52f000 r--p 00000000 fe:01 9831037           /usr/lib/x86_64-linux-gnu/libc-2.28.so
7f33ab52f000-7f33ab677000 r-xp 00022000 fe:01 9831037           /usr/lib/x86_64-linux-gnu/libc-2.28.so
7f33ab677000-7f33ab6c3000 r--p 0016a000 fe:01 9831037           /usr/lib/x86_64-linux-gnu/libc-2.28.so
7f33ab6c3000-7f33ab6c4000 ---p 001b6000 fe:01 9831037           /usr/lib/x86_64-linux-gnu/libc-2.28.so
7f33ab6c4000-7f33ab6c8000 r--p 001b6000 fe:01 9831037           /usr/lib/x86_64-linux-gnu/libc-2.28.so
7f33ab6c8000-7f33ab6ca000 rw-p 001ba000 fe:01 9831037           /usr/lib/x86_64-linux-gnu/libc-2.28.so
7f33ab6ca000-7f33ab6d0000 rw-p 00000000 00:00 0
7f33ab6ea000-7f33ab6eb000 r--p 00000000 fe:01 9830423           /usr/lib/x86_64-linux-gnu/ld-2.28.so
7f33ab6eb000-7f33ab709000 r-xp 00001000 fe:01 9830423           /usr/lib/x86_64-linux-gnu/ld-2.28.so
7f33ab709000-7f33ab711000 r--p 0001f000 fe:01 9830423           /usr/lib/x86_64-linux-gnu/ld-2.28.so
7f33ab711000-7f33ab712000 r--p 00026000 fe:01 9830423           /usr/lib/x86_64-linux-gnu/ld-2.28.so
7f33ab712000-7f33ab713000 rw-p 00027000 fe:01 9830423           /usr/lib/x86_64-linux-gnu/ld-2.28.so
7f33ab713000-7f33ab714000 rw-p 00000000 00:00 0
7ffe65a69000-7ffe65a8a000 rw-p 00000000 00:00 0         [stack]
7ffe65be0000-7ffe65be3000 r--p 00000000 00:00 0         [vvar]
7ffe65be3000-7ffe65be5000 r-xp 00000000 00:00 0         [vdso]
```

### CODE REVIEW

**Comment by zachriggle** [comment]
Two suggestions:

1) This needs to work for processes running under QEMU.  I’m not sure how
easy / possible this is without a preload but it’s worth investigating
(since process() supports QEMU to make things easy)
2) There should be programmatic access to the maps, e.g. maps[0].path.  You
can still have the __str__ return the original so that printing works.

**Comment by zer1t0** [comment]
I'm sorry that my example wasn't clear. Actually, as you suggested, it is possible to access to the different properties of each map (described in MemoryMap) as well as print thanks to its `__str__` method. Just as follows:

```
>>> from pwn import *
>>> p = process('sh')
[x] Starting local process '/usr/bin/sh'
[+] Starting local process '/usr/bin/sh': pid 7780
>>> p.maps()[0].path
'/usr/bin/dash'
>>> p.maps()[0].readable
True
>>> p.maps()[0].writable
False
>>> p.maps()[0].executable
False
>>> hex(p.maps()[0].start_addr)
'0x55b0c5b4e000'
>>> print(p.maps()[0])
55b0c5b4e000-55b0c5b52000 r--p 00000000 fe:01 9832286           /usr/bin/dash
```

Respect to qemu, I performed some tests and the output is similar to the snippet. I understand that for qemu compatibility, you refer to the ability of avoid the maps of the qemu emulator and get the maps as if the binary was executed natively. If it is possible, as you mention, it would probably require to hook qemu and create a map based on the memory allocations, which doesn't seem to be straightforward. Moreover, I don't think you could obtain an original native memory map since it is based on the emulated one. What do you think?
```
>>> from pwn import *
>>> p = process('./test-arm')
[x] Starting local process './test-arm'
[+] Starting local process './test-arm': pid 8707
>>> for map in p.maps():
...     print(map)
... 
60000000-60001000 r--p 00000000 fe:01 9862478		/usr/bin/qemu-arm-static
60001000-602ba000 r-xp 00001000 fe:01 9862478		/usr/bin/qemu-arm-static
602ba000-60532000 r--p 002ba000 fe:01 9862478		/usr/bin/qemu-arm-static
60533000-605cc000 rw-p 00532000 fe:01 9862478		/usr/bin/qemu-arm-static
605cc000-605d6000 rw-p 00000000 00:00 0
605d6000-625d4000 rwxp 00000000 00:00 0
625d4000-625d5000 ---p 00000000 00:00 0
625d5000-625f1000 rw-p 00000000 00:00 0
62f21000-63057000 rw-p 00000000 00:00 0		[heap]
7f95d000f000-7f96cf5ac000 ---p 00000000 00:00 0
7f96cf5ac000-7f96cf6ac000 rw-p 00000000 00:00 0
7f96cf6ac000-7f96cf790000 r-xp 00000000 fe:01 9862578		/usr/lib/arm-linux-gnueabihf/libc-2.28.so
7f96cf790000-7f96cf7a0000 ---p 000e4000 fe:01 9862578		/usr/lib/arm-linux-gnueabihf/libc-2.28.so
7f96cf7a0000-7f96cf7a2000 r--p 000e4000 fe:01 9862578		/usr/lib/arm-linux-gnueabihf/libc-2.28.so
7f96cf7a2000-7f96cf7a3000 rw-p 000e6000 fe:01 9862578		/usr/lib/arm-linux-gnueabihf/libc-2.28.so
7f96cf7a3000-7f96cf7a8000 rw-p 00000000 00:00 0
7f96cf7a8000-7f96cf7c2000 ---p 00000000 00:00 0
7f96cf7c2000-7f96cf7da000 r-xp 00000000 fe:01 10374584		/usr/arm-linux-gnueabihf/lib/ld-2.28.so
7f96cf7da000-7f96cf7ea000 ---p 00000000 00:00 0
7f96cf7ea000-7f96cf7eb000 r--p 00018000 fe:01 10374584		/usr/arm-linux-gnueabihf/lib/ld-2.28.so
7f96cf7eb000-7f96cf7ec000 rw-p 00019000 fe:01 10374584		/usr/arm-linux-gnueabihf/lib/ld-2.28.so
7f96cf7ec000-7f96cf7ed000 ---p 00000000 00:00 0
7f96cf7ed000-7f96cffed000 rw-p 00000000 00:00 0
7f96cffed000-7f96cffee000 r-xp 00000000 fe:01 3676832		/home/zrt/test-arm
7f96cffee000-7f96cfffd000 ---p 00000000 00:00 0
7f96cfffd000-7f96cfffe000 r--p 00000000 fe:01 3676832		/home/zrt/test-arm
7f96cfffe000-7f96cffff000 rw-p 00001000 fe:01 3676832		/home/zrt/test-arm
7f96cffff000-7f96d0000000 r--p 00000000 00:00 0
7f96d0000000-7f96d0021000 rw-p 00000000 00:00 0
7f96d0021000-7f96d4000000 ---p 00000000 00:00 0
7f96d691a000-7f96d699b000 rw-p 00000000 00:00 0
7f96d699b000-7f96d699c000 ---p 00000000 00:00 0
7f96d699c000-7f96d719c000 rw-p 00000000 00:00 0
7ffc89cf8000-7ffc89d19000 rw-p 00000000 00:00 0		[stack]
7ffc89d8e000-7ffc89d91000 r--p 00000000 00:00 0		[vvar]
7ffc89d91000-7ffc89d93000 r-xp 00000000 00:00 0		[vdso]
```

**Comment by zer1t0** [comment]
In order to increase the capabilities of the pwntools, I created a new module `heap` to parse and inspect the heap libc structures, such as bins or the malloc state.

To do this a new property method in `tubes.process` has been created, `heap_explorer`, which returns an instance of the new added `HeapExplorer` class. This class allows to access to the following items of any of the libc arenas:
* malloc_state struct
* bins => tcaches, fast bins, unsorted bin, small bins and large bins
* heap 

Also the description of the module and its classes and examples of use has been added to the documentation.

Moreover, the module has been testing in libc versions 2.19, 2.20, 2.23, 2.24, 2.25 and 2.27. However I did not find a easy way to add tests to the module since it is highly dependent of the glibc version as well as the process memory layout. 

Here I let an example of the use of the module:

```
>>> p = process('bash')
>>> hp = p.heap_explorer
>>> print(hp.arena()) # doctest: +SKIP
++++++++++++++++++++++++++++++++++++ Arena ++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
======================== Malloc State (0x7f97053fbc40) ========================
mutex = 0x0
flags = 0x1
have_fastchunks = 0x0
fastbinsY
[0] 0x20 => 0x0
[1] 0x30 => 0x0
[2] 0x40 => 0x0
[3] 0x50 => 0x0
[4] 0x60 => 0x55c4669fdc20
[5] 0x70 => 0x0
[6] 0x80 => 0x0
[7] 0x90 => 0x0
[8] 0xa0 => 0x0
[9] 0xb0 => 0x0
top = 0x55c4669ff6e0
last_remainder = 0x0
bins
Unsorted bins
[0] fd=0x55c4669fed40 bk=0x55c4669fdca0
Small bins
[1] 0x20 fd=0x7f97053fbcb0 bk=0x7f97053fbcb0
[2] 0x30 fd=0x7f97053fbcc0 bk=0x7f97053fbcc0
        ........
[61] 0x3e0 fd=0x7f97053fc070 bk=0x7f97053fc070
[62] 0x3f0 fd=0x7f97053fc080 bk=0x7f97053fc080
Large bins
[63] 0x400 fd=0x7f97053fc090 bk=0x7f97053fc090
[64] 0x440 fd=0x7f97053fc0a0 bk=0x7f97053fc0a0
        ........
[125] 0x80000 fd=0x7f97053fc470 bk=0x7f97053fc470
[126] 0x100000 fd=0x7f97053fc480 bk=0x7f97053fc480
binmap = [0x0, 0x0, 0x0, 0x0]
next = 0x7f96f8000020
next_free = 0x0
attached_threads = 0x1
system_mem = 0x21000
max_system_mem = 0x21000
================================================================================
============================ Heap (0x55c4669fd000) ============================
0x55c4669fd000 0x250 PREV_IN_USE
00 00 00 00 07 00 00 00 00 00 00 00 00 00 00 00   ................
0x55c4669fd250 0x410 PREV_IN_USE
61 61 61 0a 0a 20 76 65 72 73 69 6f 6e 20 3d 20   aaa.. version =
0x55c4669fd660 0x120 PREV_IN_USE
0f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
        ..........
0x55c4669fdca0 0x1010 PREV_IN_USE
a0 bc 3f 05 97 7f 00 00 40 ed 9f 66 c4 55 00 00   ..?.....@..f.U..
0x55c4669fecb0 0x90
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x55c4669fed40 0x910 PREV_IN_USE
a0 dc 9f 66 c4 55 00 00 a0 bc 3f 05 97 7f 00 00   ...f.U....?.....
0x55c4669ff650 0x90
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0x55c4669ff6e0 0x1e920 PREV_IN_USE
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
================================================================================
=================================== Tcaches ===================================
[4] Tcache 0x58 (7) => Chunk(0x55c4669fdb50 0x60 PREV_IN_USE) => Chunk(0x55c4669
fdaf0 0x60 PREV_IN_USE) => Chunk(0x55c4669fda90 0x60 PREV_IN_USE) => Chunk(0x55c
4669fda30 0x60 PREV_IN_USE) => Chunk(0x55c4669fd970 0x60 PREV_IN_USE) => Chunk(0
x55c4669fd910 0x60 PREV_IN_USE) => Chunk(0x55c4669fd8b0 0x60 PREV_IN_USE) => 0x0
================================================================================
================================== Fast Bins ==================================
[4] Fast Bin 0x60 (2) => Chunk(0x55c4669fdc20 0x60 PREV_IN_USE) => Chunk(0x55c46
69fdba0 0x60 PREV_IN_USE) => 0x0
================================================================================
================================ Unsorted Bins ================================
[0] Unsorted Bin (2) => Chunk(0x55c4669fed40 0x910 PREV_IN_USE) => Chunk(0x55c46
69fdca0 0x1010 PREV_IN_USE) => 0x7f97053fbca0
================================================================================
================================== Small Bins ==================================
[-] No chunks found
================================================================================
================================== Large Bins ==================================
[-] No chunks found
================================================================================
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by zer1t0** [comment]
Hello, any news here?

**Comment by heapcrash** [comment]
It looks like you've continued a great deal of development on top of this for supporting heap structures, can you reopen a new PR which has *only* the changes for memory maps?

Edit: Or force-push the older commit as HEAD of this branch, that'll work too and I can reopen the issue

Thanks!

**Pull request closed without merging**
