### PR TITLE
Fix chunked reading of ELF files

### PR DESCRIPTION
**Pull request by zachriggle**
This introduces a new dependency on 'intervaltree', which is used
to automatically select segments which are relevant for a given
virtual-address range.

This also introduces a new ELF.memory attribute, which is the tree
of memory ranges, which point at the segment objects that describe
the memory range.

These are recalculated when ELF.address is adjusted, and we have
tests for that.

This also optimizes some of the other routines to avoid the wrapped
file-seeking, and to just use the mmap.

Fixes Gallopsled/pwntools#864

### CODE REVIEW

**Comment by zachriggle** [comment]
Currently broken on the last byte

```
>>> e.read(0xf6800000, 1)
'\x00'
>>> e.read(0xf6ffffff, 1)
[ERROR] Address 0xf6ffffff does not exist in ./core.120172
```

**Comment by zachriggle** [comment]
This is technically a bug that has existed since the ELF module was introduced in 8252b6cd4754f416c5e7cd847bad4d236f79df86.

It hasn't ever broken anything before, and I'm hesitant about back-porting this medium-sized change.

I'm in the process of writing more tests, but it requires additional changes to `pwnlib.asm`.  It looks like I actually stumbled across this bug a long time ago, but worked around it by forcing the assembler to emit padding into the ELF file.

**Comment by zachriggle** [comment]
Greatly reduced the size of the changes, and added some changes to `travis/install.sh` which use Ubuntu Zesty's version of `binutils` and `qemu-static`.

It turns out that Ubuntu's Zesty packages -- for these specific packages -- run just fine on Precise.  There's no need to pull from the Pwntools PPA.

**Comment by zachriggle** [comment]
Ping @Idolf for review

**Comment by zachriggle** [comment]
Restarted a new copy of the Travis build after deleting the cache files for this PR, to ensure that there are no lingering "broken but it's in cache so it works" issues.

**Review by TethysSvensson — APPROVED** [review]
LGTM.

Is there an easy way to add a test the hits a few of the edge cases of this? (e.g. non-continuous  segments, overlapping segments)

**Comment by zachriggle** [comment]
If you look at the changes, you should see there are tests for one of those scenarios (read spans non-contiguous segments).  I can't get `objdump` to emit a malformed ELF which has overlapping segments.

What we *could* do is just have each `DT_LOAD` take precedence over any previous `DT_LOAD` regions, which would have a similar effect, and is presumably the "most correct" way to do it.

**Comment by zachriggle** [comment]
Added bad24ee to address the second half of https://github.com/Gallopsled/pwntools/pull/865#pullrequestreview-18231211

**Pull request merged**
