### PR TITLE
Resolve feature regression in hexdump(..., cyclic=True)

### PR DESCRIPTION
**Pull request by zachriggle**
This code wasnt updated when the code was changed to operate on file descriptors.

Additionally, there was a functional regression, that the first line would be skipped.

Fixes: Gallopsled/pwntools#836
Caused by: Gallopsled/pwntools#695 (d65991d)

### CODE REVIEW

**Comment by zachriggle** [comment]
There are no tests for any of the `hexdump` functionality, because it currently does not have any mechanism to **NOT** emit ANSI color codes.

**Comment by zachriggle** [comment]
## Before

```
>>> print hexdump(fit({64: 'X'*20}, length=0xc0), cyclic=1)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-d2d4799be547> in <module>()
----> 1 print hexdump(fit({64: 'X'*20}, length=0xc0), cyclic=1)

/Users/riggle/pwntools/pwnlib/util/fiddling.py in hexdump(s, width, skip, hexii, begin, style, highlight, cyclic)
    707                                   style,
    708                                   highlight,
--> 709                                   cyclic))
    710
    711 def negate(value, width = None):

/Users/riggle/pwntools/pwnlib/util/fiddling.py in hexdump_iter(fd, width, skip, hexii, begin, style, highlight, cyclic)
    629
    630     if cyclic:
--> 631         update_cyclic_pregenerated(len(s))
    632
    633     numb = 0

NameError: global name 's' is not defined
```

## After

```
>>> print hexdump(fit({64: 'X'*20}, length=0xc0), cyclic=1)
00000000  61 61 61 61  62 61 61 61  63 61 61 61  64 61 61 61  │aaaa│baaa│caaa│daaa│
*
00000040  58 58 58 58  58 58 58 58  58 58 58 58  58 58 58 58  │XXXX│XXXX│XXXX│XXXX│
00000050  58 58 58 58  76 61 61 61  77 61 61 61  78 61 61 61  │XXXX│vaaa│waaa│xaaa│
00000060  79 61 61 61  7a 61 61 62  62 61 61 62  63 61 61 62  │yaaa│zaab│baab│caab│
*
000000c0
```

**Comment by zachriggle** [comment]
Added @br0ns as a reviewer since his commit d65991d4 caused the regression

**Review by TethysSvensson — APPROVED** [review]
LGTM

**Comment by TethysSvensson** [comment]
Ping me once this lands, and I will forwards-merge + do a new release.

**Comment by zachriggle** [comment]
Don't merge this yet, I broke something in attempting to make the code less unreadable.

**Comment by TethysSvensson** [comment]
Sure, I will leave merging to you. Just ping me once you want the forward merge + release. :)

**Comment by zachriggle** [comment]
What the fuck did I even do to this.  Wat.

**Comment by zachriggle** [comment]
@Idolf ping

**Comment by TethysSvensson** [comment]
Forward-merge + release done.

**Pull request merged**
