### PR TITLE
Added support for generating a Dash docset.

### PR DESCRIPTION
**Pull request by martian**
I use Dash to search my documentation offline.
Here is a patch to generate a docset for pwntools.

Dash docsets can be read by various applications:
Dash         OS X, iOS         https://kapeli.com
Zeal         Linux, Windows    https://zealdocs.org
Velocity     Windows           http://velocity.silverlakesoftware.com
LovelyDocs   Android           http://lovelydocs.io
dasht        POSIX             https://github.com/sunaku/dasht
Helm Dash    emacs             https://github.com/areina/helm-dash

### CODE REVIEW

**Comment by zachriggle** [comment]
As someone unfamiliar with Dash docs, what does it provide?

**Comment by martian** [comment]
In case it wasn't clear: the docsets provide no new information, just the existing documentation in a format compatible with the Dash application (on OSX) and others.

It provides fast, indexed, offline documentation for many programming languages and libraries. See kapeli.com for screenshots.

**Comment by zachriggle** [comment]
You need to change `/usr/bin/python` to `/usr/bin/env python2`.

**Comment by zachriggle** [comment]
Cherry-picked to binjitsu/binjitsu@7f236f5064841b3c7889d4c9cc3bd041474a33ad

Docset is available here:
https://github.com/binjitsu/binjitsu/blob/dash/docs/build/dash/pwntools.tgz

**Pull request merged**
