### PR TITLE
Added section_addr method

### PR DESCRIPTION
**Pull request by Hellsender01**
Added section_addr method in elf object to get address of sections in elf like bss,data,text,etc.

```python
from pwn import *
elf = ELF('file',checksec=False)
elf.section_addr('.bss')
hex(elf.section_addr('.text'))
```
```bash
>>> 134518320
>>> 0x8048340
```
# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

## Changelog

After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  
You can look at the existing changelog for examples of how to do this.

### CODE REVIEW

**Review by Arusekk — APPROVED** [review]
A test would be nice

**Comment by Hellsender01** [comment]
what kind of test??

**Comment by Arusekk** [comment]
A doctest, like
```py
def function(x):
    '''
    Description...
    
    Example:
        >>> function(7)
        17
    '''
```

You can find more real examples throughout the codebase, and see TESTING.md for more info about our tests.

**Comment by heapcrash** [comment]
Needs some tests (we have lots of ELF files by pulling out a file from `pwnlib.data.elf.relro.path`)

Also needs a CHANGELOG update

**Comment by Hellsender01** [comment]
Tested on both x64 and x86 elfs with and without PIE enabled, working fine

**Comment by Arusekk** [comment]
There is no binary named `chal` on the test machine. Our tests are standard Python '[doctests](https://docs.python.org/dev/library/doctest.html)', i.e. the code of examples is extracted from the documentation strings, and actually executed, output compared against 'expected' output. See the "Checks" tab of the pull request for a test report (there is a failing 'Continuous Integration / test' entry).

Search the code for `pwnlib.data.elf` for examples of test cases involving actual binaries.

**Pull request closed without merging**
