### PR TITLE
Merged the pwntools-ancient branch

### PR DESCRIPTION
**Pull request by Idolf**
This PR does not change any files. It is only here to keep history alive.

I am creating this PR so the commits in the pwntools-ancient branch will continue to live even after we delete the pwntools-ancient branch.

### CODE REVIEW

**Comment by Idolf** [comment]
@zachriggle, @br0ns : I think we should merge this and tag the old pwntools-ancient branch with a tag (such as 0.9). Is that okay with both of you?

**Comment by zachriggle** [comment]
Why not just migrate it to its own repo?  Or leave the branch?

**Comment by Idolf** [comment]
I would like to remove the branch and add a tag instead. If we do this, we would be down to having 4 branchs: stable, beta, dev, gh-pages.

**Comment by zachriggle** [comment]
You should be able to just tag the branch and delete it, no merge necessary.

**Comment by Idolf** [comment]
Huh. Sure, I guess. If that works, then it seems like a better solution.

**Comment by Idolf** [comment]
That is a much better solution. I am doing that now. If @br0ns disagrees we can change it afterwards.

**Comment by br0ns** [comment]
:+1:

**Pull request closed without merging**
