### PR TITLE
update cache directories

### PR DESCRIPTION
**Pull request by 152334H**
> Please provide a high-level explanation of what this pull request is for.

Pwntools uses `~/.cache/.pwntools-cache*` now, not `~/.pwntools-cache`?

> After creating your Pull Request, please add and push a commit that updates the changelog for the appropriate branch.  

Doing PR to verify that I'm not missing something obvious

### CODE REVIEW

**Comment by zachriggle** [comment]
This will cause everybody who put `never` in the update file to have to re-do that step 😢

**Comment by 152334H** [comment]
Will it? It was my impression that people using `~/.pwntools-cache-*` already had life broken for them...

**Comment by zachriggle** [comment]
Putting the "disable" file inside of the pwntools **CACHE** directory was probably a bad move in the first place.

I must have missed that change :(

**Comment by Arusekk** [comment]
This change is reflecting in the documentation what was already present from #1420 and before.

**Pull request merged**
