### PR TITLE
Removed the early import of some libraries.

### LINKED ISSUE #736: pwntools is slow to import, because of update.py
https://github.com/Gallopsled/pwntools/pull/659

```
$ time python -c "from pwn import *"
real    0m1.624s
user    0m1.484s
sys 0m0.120s
```

because of "import pip"

### PR DESCRIPTION
**Pull request by TethysSvensson**
This should mostly fix #736, though we will still need to look at other imports.

### CODE REVIEW

**Comment by TethysSvensson** [comment]
@zachriggle: If you agree with this change, then it is ready to merge.

**Comment by zachriggle** [comment]
LGTM if you fix the Codacy issues

**Review by zachriggle — CHANGES_REQUESTED** [review]
There are some issues from Codacy.

**Comment by zachriggle** [comment]
I vote that #738 is a better solution than deferred imports

**Comment by TethysSvensson** [comment]
I vote #738 as well.

**Pull request closed without merging**
