### PR TITLE
Format String Automation

### LINKED ISSUE #682: Format String Module Inefficiencies
The current `pwnlib.fmtstr` module was an accepted contribution from a third party, but is not particularly efficient (the arguments are backward from normal mechanisms).

I [asked](https://github.com/hellman/libformatstr/issues/5) @hellman to license his code under the MIT license, and he obliged.

We should just use his code instead, since it's what I use, and it's what everybody else uses, and save everyone from needing to download it and `import libformatstr`.

### PR DESCRIPTION
**Pull request by zachriggle**
This is an in-progress commit series to resolve #682 by introducing a much more robust format string mechanism.

Currently, our format-string module is different from and inferior to the benchmark `libformatstr` from @hellman

However, that library does not do automatic discovery, and does not work under a variety of circumstances (e.g. 64-bit).

### CODE REVIEW

**Comment by zachriggle** [comment]
I lost all of the documentation that I had on this :(

**Comment by zachriggle** [comment]
Nevermind, found it! Hurray!

**Comment by zachriggle** [comment]
I'm actually still working on this occasionally, it's just slow-going

**Comment by zachriggle** [comment]
Housekeeping: Closing this Pull Request so that it doesn't show as outstanding.

I might work on this in the future at some point, but have no cycles currently.

**Comment by zachriggle** [comment]
Update Dec. 2017: The current `fmtstr` module still needs to be rewritten.  Intermediate work is on a [branch `format-string` on my fork](https://github.com/zachriggle/pwntools/blob/format-string/pwnlib/formatstring.py).

You can see the design and documentation [here](https://raw.githubusercontent.com/zachriggle/pwntools/format-string/docs/source/fmtstr.rst).

**Comment by iromise** [comment]
Sadly for now, I am also busy for dealing final exam. May be in January, I will have some time to work on this branch.

**Comment by zachriggle** [comment]
Let me know if you have any questions, it’s a feature I would love to have
completed ❤️

**Comment by iromise** [comment]
@zachriggle  sure.

**Pull request closed without merging**
