### PR TITLE
Remove data_files

### PR DESCRIPTION
**Pull request by nella17**
> Warning `data_files` is deprecated. It does not work with wheels, so it should be avoided.

https://setuptools.readthedocs.io/en/latest/setuptools.html

### CODE REVIEW

**Comment by zachriggle** [comment]
What is the suggested replacement? We don't want to remove these files as they're necessary e.g. `requirements.txt` and `README.md`.

**Comment by nella17** [comment]
I don’t known, I’m not familiar with `setuptools`.
I create this issue because install this repo on macOS install those `data_file` in wrong directory(`/usr/local/`)

**Comment by SuperStormer** [comment]
Is there any reason why we need to install `requirements.txt` and `README.md`? I thought `requirements.txt` is only needed to install the library itself.  This should also fix #1173, which is still occurring and shouldn't have been closed.

**Comment by Arusekk** [comment]
Please apply my suggestion from https://github.com/Gallopsled/pwntools/issues/1173#issuecomment-410513360 as a compromise

**Comment by Arusekk** [comment]
This may be reconsidered in the future.

**Pull request merged**
