### PR TITLE
use binutils targeting elf's architecture, instead of default

### PR DESCRIPTION
**Pull request by ChiChou**

### CODE REVIEW

**Comment by zachriggle** [comment]
The problem with this approach is that it becomes impossible to disassemble Thumb code in an ARM binary, since `arch` will never be `'thumb`'.

**Comment by zachriggle** [comment]
Perhaps it would be sufficient to do something like:

```py
def diasm(..., arch=None):
    if arch is None: arch = self.arch
    ....
    return disasm(..., arch=arch)
```

**Comment by zachriggle** [comment]
Nah, I still don't like that since I can't do it in a `context.local(arch='arm')` block and get what I would expect.

**Comment by zachriggle** [comment]
tl;dr @ChiCou should use `context.binary` to auto-set `context.arch`, or set `context.arch` manually.

**Comment by ChiChou** [comment]
@zachriggle I knew the context trick but I thought it's a little bit confusing. Thanks for pointing out the Thumb problem.

**Pull request closed without merging**
