### PR TITLE
Add code for libcdb lookups

### PR DESCRIPTION
**Pull request by zachriggle**
Adds support to DynELF to perform lookups on-the-fly given only a GNU Build ID.

These are useful, in that it's 20 bytes of data which for almost any libc I can find, are at a static offset from the library base.  This saves time on over-the-wire lookups, and may be useful in scenarios where the number of leaks we can perform is restricted.

Additionally, this includes some fixes/enhancements to MemLeak and ELF, some of which are required for this functionality (I just grabbed the whole file from Binjitsu rather than pick individual features).

### CODE REVIEW

**Comment by zachriggle** [comment]
Here's the ropasaurus example using it:

```
[+] Started program './ropasaurusrex-85a84f36f81e11f720b1cf5ea0d1fb0d5a603c0d'
[*] '/usr/local/google/home/riggle/pwntools-write-ups/2013/pctf/ropasaurus/ropasaurusrex-85a84f36f81e11f720b1cf5ea0d1fb0d5a603c0d'
    Arch:          i386-32-little
    RELRO:         No RELRO
    Stack Canary:  No canary found
    NX:            NX enabled
    PIE:           No PIE
[*] Stage 1 Rop:
    0x0000:        0x804832c (read)
    0x0004:        0x80483bf (add esp, 4; pop ebx; pop ebp; ret)
    0x0008:              0x0
    0x000c:        0x8049828
    0x0010:            0x100
    0x0014:        0x80483c3 (pop ebp; ret)
    0x0018:        0x8049824
    0x001c:        0x80482ea (leave; ret)
[+] Loading from '/usr/local/google/home/riggle/pwntools-write-ups/2013/pctf/ropasaurus/ropasaurusrex-85a84f36f81e11f720b1cf5ea0d1fb0d5a603c0d': 0xf77be938
[+] Resolving 'system' in 'libc.so': 0xf77be938
[*] Downloading data from GitHub
[+] Downloading 'https://raw.githubusercontent.com/zachriggle/libcdb/master/build_id/f9b5531180de2f0ce620bc03b5fc4d7f8570fd18': 71B
[+] Downloading 'https://raw.githubusercontent.com/zachriggle/libcdb/master/libc/libc6_2.19-0ubuntu6.6_i386/data/lib/i386-linux-gnu/libc-2.19.so': 86B
[+] Downloading 'https://raw.githubusercontent.com/zachriggle/libcdb/master/sha256/1d286c652800917b618e97528409d70354ba9964f6b42d20bf5466a2b0c22400': 1.67MB
[*] Switching to interactive mode
$ id
```

**Comment by zachriggle** [comment]
This also closes #527

**Comment by kokjo** [comment]
Sorry this commit is not happening. I do not want dynelf to do anything but dynelf'ing.
I do not want to rely on some libc lookup service when i ask pwntools to leak and do pointer chasing.
However its a nice feature that might speed things up, and i would like it to be optional.

Also it is very easy to replace ons build id, just to fuck up this technique, and i believe that dynelf is more 'pure' and reliable

**Comment by zachriggle** [comment]
I pulled the code out to be entirely optional, and accessible via `DynELF(...).libc()`.  It'll look up the Build ID, download the file, return an `ELF` object.  The code for `.resolve()` was restored to its previous functionality.

Unrelated, it looks like I pulled in a few extra changes which make `ELF` work better with alternate architectures, and fixed a big which @br0ns pointed out on IRC the other day, which I'd fixed a while back (ROP i386 vs x86 naming).

**Pull request merged**
