### PR TITLE
Update Sphinx in order to fix jinja2 deprecated dependency.

### PR DESCRIPTION
**Pull request by gogo2464**
# Pwntools Pull Request

Fix the error `ImportError: cannot import name 'environmentfilter' from 'jinja2'` on sphinx on the travis cicd.

### CODE REVIEW

**Comment by gogo2464** [comment]
Seems ready to merge. I do not have balance for the file CI.yml anymore.

**Comment by Arusekk** [comment]
Could this go into a single file, with just the differences split out? IIRC requirements.txt has some form of including other requirement files (`-r file.txt` or such). If you don't know how it works, I will do it on the coming days.

**Comment by gogo2464** [comment]
Do not worry. Ijust googled it on internet.

**Comment by gogo2464** [comment]
Perfect. Ready to merge.

**Comment by Arusekk** [comment]
Wow, I didn't know that, it is perfect! Can you change == 2.7.x to < 3.0 and == 3.8.x to >= 3.0 (so that it keeps working after any of them suddenly gets an update)?

**Comment by gogo2464** [comment]
Fixed. Ready to merge. :)

**Pull request merged**
