### PR TITLE
Add more adb commands.

### PR DESCRIPTION
**Pull request by gregthedoe**
1. Create a simple function to run adb shell command.
2. Add install and uninstall of android packages.

### CODE REVIEW

**Comment by TethysSvensson** [comment]
I think this looks reasonable, but I have not looked at the adb code before. @zachriggle, what do you think?

@gregthedoe: Could you add a note to the changelog about this as well?

@zachriggle: This decreases coverage, as the adb is untested. Is there any way for us to test this code?

**Comment by zachriggle** [comment]
I was working last night on getting some stuff to test via an emulator on
Travis, but got hung up because my DO VPS doesn't have the disk space or
RAM required to run one.

**Comment by zachriggle** [comment]
Since #709 landed, this will need to be rewritten.
Since #705 landed, we have doctests which use an Android 5.0 Lollipop emulator image

**Comment by zachriggle** [comment]
This is obsolete as of 4893819

**Pull request closed without merging**
