### PR TITLE
__str__ to __bytes__ in python2

### PR DESCRIPTION
**Pull request by layderv**
# Pwntools Pull Request

Thanks for contributing to Pwntools!  Take a moment to look at [`CONTRIBUTING.md`][contributing] to make sure you're familiar with Pwntools development.

Please provide a high-level explanation of what this pull request is for.
As discussed in https://github.com/Gallopsled/pwntools/pull/1505, we want to have a compatibility decorator between Python2/3 to set `__str__` to `__bytes__` in Python2.

## Testing

Pull Requests that introduce new code should try to add doctests for that code.  See [`TESTING.md`][testing] for more information.

```
> cat test.py 
from pwn import *
r = ROP([])
r.raw(255)
r.raw('aaa')
print(r.dump())
print(hexdump(r.chain()))
print(hexdump(bytes(r)))
print(hexdump(str(r)))

> python2 test.py
0x0000:             0xff
0x0004:            'aaa' 'aaa'
00000000  ff 00 00 00  61 61 61                               │····│aaa│
00000007
00000000  ff 00 00 00  61 61 61                               │····│aaa│
00000007
00000000  ff 00 00 00  61 61 61                               │····│aaa│
00000007

> python3 test.py
0x0000:             0xff
0x0004:           b'aaa' 'aaa'
00000000  ff 00 00 00  61 61 61                               │····│aaa│
00000007
00000000  ff 00 00 00  61 61 61                               │····│aaa│
00000007
00000000  52 4f 50 28  5b 5d 29                               │ROP(│[])│
00000007
```

## Target Branch

Depending on what the PR is for, it needs to target a different branch.

You can always [change the branch][change] after you create the PR if it's against the wrong branch.

| Branch   | Type of PR                                                       |
| -------- | ---------------------------------------------------------------- |
| `dev`    | New features, and enhancements
| `dev`    | Documentation fixes and new tests
| `stable` | Bug fixes that affect the current `stable` branch
| `beta`   | Bug fixes that affect the current `beta` branch, but not `stable`
| `dev`    | Bug fixes for code that has never been released

[contributing]: https://github.com/Gallopsled/pwntools/blob/dev/CONTRIBUTING.md
[testing]: https://github.com/Gallopsled/pwntools/blob/dev/TESTING.md
[change]: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

### CODE REVIEW

**Comment by layderv** [comment]
@Arusekk is this what you had in mind?

**Comment by Arusekk** [comment]
This is just what I meant, great!
The tests are failing, though, please try to make them pass.

EDIT: this is probably a false negative; strange that core files spawn in such a non-deterministic way, probably this should be addressed one day

**Comment by layderv** [comment]
It's fixed now.
Some modules relied on the previous behavior. If you agree, we can merge this change and make it available for everyone else to use too

**Comment by Arusekk** [comment]
Merged previous version via d944a9

**Pull request closed without merging**
