### PR TITLE
Fix ARM PLT parsing, and big-endian ARM emulation

### PR DESCRIPTION
**Pull request by zachriggle**
Fixes some problems introduced by #899

### CODE REVIEW

**Comment by zachriggle** [comment]
If the 3.5.0 release happens before this is closed, I may need to revert #899. At a minimum, we need better handling of Unicorn errors and exceptions.  I think a high-level "except Exception" handler should do the trick, but it still needs to be actually committed.

**Comment by zachriggle** [comment]
@neoneo can you take a look now?  I've added your suite of files as a doctest which should be getting run now.

**Comment by zachriggle** [comment]
Whoops, I meant @nneonneo

**Comment by nneonneo** [comment]
@zachriggle: I finally got a chance to look at it, and it doesn't seem functional. Running on test-arm, I get a warning:

    [!] Could not populate PLT: 66536L

If I disable the relevant try/except, I get the following traceback:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/checksec", line 11, in <module>
    load_entry_point('pwntools==3.6.0.dev0', 'console_scripts', 'checksec')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwntools-3.6.0.dev0-py2.7.egg/pwnlib/commandline/common.py", line 32, in main
    pwnlib.commandline.main.main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwntools-3.6.0.dev0-py2.7.egg/pwnlib/commandline/main.py", line 51, in main
    commands[args.command](args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwntools-3.6.0.dev0-py2.7.egg/pwnlib/commandline/checksec.py", line 37, in main
    e = ELF(f.name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwntools-3.6.0.dev0-py2.7.egg/pwnlib/elf/elf.py", line 316, in __init__
    self._populate_plt()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwntools-3.6.0.dev0-py2.7.egg/pwnlib/elf/elf.py", line 826, in _populate_plt
    self.plt[inv_symbols[target]] = address
KeyError: 66536L
```

The contents of `inv_symbols` are

    {132928: u'printf', 132932: u'__stack_chk_fail', 132968: u'__stack_chk_guard', 132940: u'__gmon_start__', 132944: u'srand', 132936: u'__libc_start_main', 132948: u'__isoc99_scanf', 132952: u'abort', 132924: u'strtol'}

so I don't know why it's accessing 66536L (0x103e8).

This sort of error occurs with *all* the -arm- and -thumb- test binaries, making the PLT useless.

**Comment by zachriggle** [comment]
Really? There's a test that's running that's checking these automatically: https://github.com/zachriggle/pwntools/blob/eedb4b429e6a95d84243f493cb72d95d96260bb3/pwnlib/elf/elf.py#L779-L788

```py
path = pwnlib.data.elf.path
for test in glob(os.path.join(path, 'test-*')):
    test = ELF(test)
    assert '__stack_chk_fail' in test.got, test
    if test.arch != 'ppc':
        assert '__stack_chk_fail' in test.plt, test
```

Here's what I get when I run that snippet:

```
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64'
    Arch:     aarch64-64-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64-big'
    Arch:     aarch64-64-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64-big-pie'
    Arch:     aarch64-64-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64-big-relro'
    Arch:     aarch64-64-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64-big-relro-pie'
    Arch:     aarch64-64-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64-pie'
    Arch:     aarch64-64-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64-relro'
    Arch:     aarch64-64-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-aarch64-relro-pie'
    Arch:     aarch64-64-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm-big'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm-big-pie'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm-big-relro'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm-big-relro-pie'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm-pie'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm-relro'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-arm-relro-pie'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-mips-big'
    Arch:     mips-32-big
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX disabled
    PIE:      No PIE (0x400000)
    RWX:      Has RWX segments
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-mips-big-pie'
    Arch:     mips-32-big
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX disabled
    PIE:      PIE enabled
    RWX:      Has RWX segments
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-mips-big-pie-relro'
    Arch:     mips-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX disabled
    PIE:      PIE enabled
    RWX:      Has RWX segments
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-mips-big-relro'
    Arch:     mips-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX disabled
    PIE:      No PIE (0x400000)
    RWX:      Has RWX segments
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb-big'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb-big-pie'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb-big-relro'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb-big-relro-pie'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb-pie'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb-relro'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-thumb-relro-pie'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x64'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
    FORTIFY:  Enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x64-pie'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
    FORTIFY:  Enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x64-relro'
    Arch:     amd64-64-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
    FORTIFY:  Enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x64-relro-pie'
    Arch:     amd64-64-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
    FORTIFY:  Enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x86'
    Arch:     i386-32-little
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x8048000)
    FORTIFY:  Enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x86-pie'
    Arch:     i386-32-little
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
    FORTIFY:  Enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x86-relro'
    Arch:     i386-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x8048000)
    FORTIFY:  Enabled
[*] '/Users/riggle/pwntools/pwnlib/data/elf/test-x86-relro-pie'
    Arch:     i386-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
    FORTIFY:  Enabled
```

**Comment by nneonneo** [comment]
So I lied - apparently, these errors occur at the end of PLT parsing since you resolve the addresses in reverse order, so in the end it's just a "harmless" but somewhat annoying warning.

Do you have any insight into why the emulation is trying to access addresses other than the GOT addresses it should be touching?

**Comment by zachriggle** [comment]
I mean we're blindly emulating every 4-byte-aligned address in the PLT, those instructions may do any number of weird things.

In any case, I see *no* error messages, per the above output.

**Comment by nneonneo** [comment]
That's really odd - I get

```
[!] Could not populate PLT: 66536L
[*] 'devel/pwntools/relro_now/test-arm'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 66536L
[*] 'devel/pwntools/relro_now/test-arm-big'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 1400L
[*] 'devel/pwntools/relro_now/test-arm-big-pie'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[!] Could not populate PLT: 66568L
[*] 'devel/pwntools/relro_now/test-arm-big-relro'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 1432L
[*] 'devel/pwntools/relro_now/test-arm-big-relro-pie'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[!] Could not populate PLT: 1400L
[*] 'devel/pwntools/relro_now/test-arm-pie'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[!] Could not populate PLT: 66568L
[*] 'devel/pwntools/relro_now/test-arm-relro'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 1432L
[*] 'devel/pwntools/relro_now/test-arm-relro-pie'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[!] Could not populate PLT: 66536L
[*] 'devel/pwntools/relro_now/test-thumb'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 66536L
[*] 'devel/pwntools/relro_now/test-thumb-big'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 1400L
[*] 'devel/pwntools/relro_now/test-thumb-big-pie'
    Arch:     arm-32-big
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[!] Could not populate PLT: 66568L
[*] 'devel/pwntools/relro_now/test-thumb-big-relro'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 1432L
[*] 'devel/pwntools/relro_now/test-thumb-big-relro-pie'
    Arch:     arm-32-big
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[!] Could not populate PLT: 1400L
[*] 'devel/pwntools/relro_now/test-thumb-pie'
    Arch:     arm-32-little
    RELRO:    No RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
[!] Could not populate PLT: 66568L
[*] 'devel/pwntools/relro_now/test-thumb-relro'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      No PIE (0x10000)
[!] Could not populate PLT: 1432L
[*] 'devel/pwntools/relro_now/test-thumb-relro-pie'
    Arch:     arm-32-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
```

Those errors are KeyErrors from the aforementioned lines.

**Comment by zachriggle** [comment]
Are you testing against the current `Gallopsled/pwntools@dev` branch?  And have you done `pip install --upgrade --editable .`?  The `--upgrade` part is important, since your Unicorn may be out-of-date and causing weird problems.

**Comment by nneonneo** [comment]
I upgraded to unicorn 1.0.0 (latest as of today) and still get the same errors. I'm also on the latest dev/ branch.

**Comment by zachriggle** [comment]
Works for me, locally on mac OS, in my Ubuntu VMs, and in the provided Docker images.

https://gist.github.com/zachriggle/79e861ea09b20d7808f67c64936362e1

**Comment by zachriggle** [comment]
Also, it looks like the files that you're testing are *not* the same files as I'm testing.  Your `relro_now` binaries are at a different path.  I'm using the original corpus of binaries that you provided.

**Comment by zachriggle** [comment]
Just committed 664622fa0720c9d38508a0bc7b96de8c0d9a4340

It appears the issue is that the binaries that I committed for the test-cases are stripped (to save space, and ensure everything worked without symbols) while you were testing with the original non-stripped binaries.

We were adding the non-GOT symbols to the valid PLT targets, but not to the inverted symbol lookup.

**Comment by zachriggle** [comment]
As an example, `test-arm-big` now gets the following PLT entries:

```
[DEBUG] PLT 0x103d4 $d
[DEBUG] PLT 0x103d8 $a
[DEBUG] PLT 0x103e0 strtol
[DEBUG] PLT 0x103f4 printf
[DEBUG] PLT 0x10400 __stack_chk_fail
[DEBUG] PLT 0x1040c __libc_start_main
[DEBUG] PLT 0x10418 __gmon_start__
[DEBUG] PLT 0x10424 srand
[DEBUG] PLT 0x10430 __isoc99_scanf
[DEBUG] PLT 0x1043c abort
```

After stripping everything, it is reduced to:

```
[DEBUG] PLT 0x103e0 strtol
[DEBUG] PLT 0x103f4 printf
[DEBUG] PLT 0x10400 __stack_chk_fail
[DEBUG] PLT 0x1040c __libc_start_main
[DEBUG] PLT 0x10418 __gmon_start__
[DEBUG] PLT 0x10424 srand
[DEBUG] PLT 0x10430 __isoc99_scanf
[DEBUG] PLT 0x1043c abort
```

I'm not sure what the `$a` and `$d` symbols are for, but they are here:

```
>>> hex(e.symbols['$a'])
'0x103e8'
>>> hex(e.symbols['$d'])
'0x103e0'
```

I'm not sure why those entries have symbols -- since they overlap with PLT entries -- but they definitely exist as stand-alone symbols.

```
$ greadelf -a test-arm-big | grep 103e
    89: 000103e0     0 NOTYPE  LOCAL  DEFAULT   12 $d
    90: 000103e4     0 NOTYPE  LOCAL  DEFAULT   12 $t
    91: 000103e8     0 NOTYPE  LOCAL  DEFAULT   12 $a
```

Since these don't really *hurt* anything, and are apparently valid (even if not very useful), I'm inclined to leave them in place.

**Pull request merged**
