### PR TITLE
Workaround for to new pyelftools

### PR DESCRIPTION
**Pull request by matedealer**
Since version 0.25 of pyelftools has some changes, installed version must be 0.24.
Will fix : #1189

### CODE REVIEW

**Comment by rickyz** [comment]
Oops, just saw this - here's an alternate pull request which tries to support pyelftools >= 0.25 by importing both names: https://github.com/Gallopsled/pwntools/pull/1191

**Comment by zachriggle** [comment]
Can you add a comment on the try/catch block to explain the reason? Thanks!

**Comment by disconnect3d** [comment]
Bump: afaik ppl are still struggling with pwntools failing, so might be good to resolve it some way :<
(https://github.com/Gallopsled/pwntools/pull/1191 - this works for me)

**Comment by zachriggle** [comment]
Fixed with `7467402e`, will cut a new release today

**Pull request closed without merging**
