### PR TITLE
Add fault_addr emulation support for call rdx

### PR DESCRIPTION
**Pull request by HenryHoggard**
Fixes `fault_addr` emulation for `call rdx`

Before fix
```
print core.fault_addr
0
```

After fix
```
print core.fault_addr
7016996846897815923
```

Also adds `Fault:   <addr>` eg `Fault:  0x6161617461616173` to the information printed about the crash.

### CODE REVIEW

**Comment by zachriggle** [comment]
Can you dig into specifically why `fault_addr` is not set correctly?

See the other bug that added this emulation in the first place for the type of analysis I mean -- we dug down into the kernel source to find the specific reason.

**Comment by zachriggle** [comment]
Please merge `dev` or rebase, thanks!

**Comment by heapcrash** [comment]
This needs to be updated with a `b` prefix for Python3

**Comment by heapcrash** [comment]
Closing this out since the PR is two+ years old.  Please rebase your changes on top of the current `dev` branch or create a new PR to get this merged.

**Pull request closed without merging**
