### PR TITLE
Handle errors during ssh.checksec()

### PR DESCRIPTION
**Pull request by zachriggle**
Closes Gallopsled/pwntools#916

### CODE REVIEW

**Comment by TethysSvensson** [comment]
Does this need a new release?

**Comment by zachriggle** [comment]
No, it affects `beta` and was merged there directly.  It'll get auto-merged into `dev` for the next release (or maybe I already did it?)

**Comment by TethysSvensson** [comment]
I can do a beta release without doing a stable release if you want?

**Comment by TethysSvensson** [comment]
And yes, this is already in dev.

**Comment by zachriggle** [comment]
I mean you can, I don't know who actually uses `beta`

**Pull request merged**
