### PR TITLE
Use musl to generate constants for Linux

### PR DESCRIPTION
**Pull request by zachriggle**
Related to #672

### CODE REVIEW

**Comment by zachriggle** [comment]
Note that we change from ~1000 to now having ~6000 constants for each architecture.

You'd think this would effect load times, but only the first time that pyc files are generated.

Current `dev` tip of tree, after a few loads:

    python -c 'from pwn import *'  0.16s user 0.10s system 89% cpu 0.288 total

This branch:

    python -c 'from pwn import *'  0.16s user 0.10s system 88% cpu 0.291 total

**Comment by zachriggle** [comment]
Currently struggling with some deficiencies of `swig`.  Namely, it neglects to generate constants for e.g.:

```
47:#define INADDR_ANY        ((in_addr_t) 0x00000000)
48:#define INADDR_BROADCAST  ((in_addr_t) 0xffffffff)
49:#define INADDR_NONE       ((in_addr_t) 0xffffffff)
50:#define INADDR_LOOPBACK   ((in_addr_t) 0x7f000001)
52:#define INADDR_UNSPEC_GROUP     ((in_addr_t) 0xe0000000)
53:#define INADDR_ALLHOSTS_GROUP   ((in_addr_t) 0xe0000001)
54:#define INADDR_ALLRTRS_GROUP    ((in_addr_t) 0xe0000002)
55:#define INADDR_MAX_LOCAL_GROUP  ((in_addr_t) 0xe00000ff)
```

Because the cast can't be evaluated by the preprocessor.  Using a `#define in_addr_t` breaks preprocessing elsewhere or fails to do what you'd hope.

Need to do some `sed` magic.

**Comment by zachriggle** [comment]
Looks like musl doesn't define e.g. `__NR_open` for AArch64.

**Review by TethysSvensson — APPROVED** [review]

**Comment by zachriggle** [comment]
Per #896 this is intended behavior

**Comment by zachriggle** [comment]
I've updated the FreeBSD and CGC constants generators to use the same Makefile vs `sh` script.

I've also removed all of the `dietlibc` headers, and fixed up the licenses.

**Comment by zachriggle** [comment]
I've also regenerated all of the syscall stubs, we gain about 20 additional ones (`pwritev2`, `name_to_handle_at`, `fadvise`, `execveat`, etc.).

**Comment by zachriggle** [comment]
Also, our generation for constant header files is now basically dumping the output of `constgrep` into a header file.

**Comment by zachriggle** [comment]
This is officially stalled, I haven't had time to work on this in a while.  I'm leaving the PR open for another while, since Pull Requests are free 😄

**Comment by zachriggle** [comment]
Housekeeping: Closing this Pull Request so that it doesn't show as outstanding.

I might work on this in the future at some point, but have no cycles currently.

**Pull request closed without merging**
