### PR TITLE
fixes #351 syscall can now accept 7 arguments

### LINKED ISSUE #351: i386.linux.syscall does not accept a 7 argument
as man syscall: ebp is the seventh arguemnt to syscalls on x86, however this is not implementet in i386.linux.syscall.

### PR DESCRIPTION
**Pull request by kokjo**

### CODE REVIEW

**Comment by kokjo** [comment]
I don't think its my fault that travis is failing, its something related to tubes and ssh, its not finding /tmp/foo

**Comment by br0ns** [comment]
Just a hiccup.  If that happens you can manually restart Travis.

**Comment by zachriggle** [comment]
While we're at it, can we get some doctests for the `syscall` templates?  

Also, the documentation does not state anything about the arguments.

**Comment by zachriggle** [comment]
Nevermind, I see them now, they're just not in this commit.

Can we *extend* the doctests to include the 7th argument?

**Comment by IdolfHatler** [comment]
Once someone extends the documentation and actually *tests* that the manpage is right, I think we should merge this.

**Comment by br0ns** [comment]
Tested.  Works.

**Comment by br0ns** [comment]
Added doctest.  Merging when Travis says go.

**Pull request merged**
