### PR TITLE
Add aliases for all tube methods for read*=recv* and write*=send*

### PR DESCRIPTION
**Pull request by zachriggle**
Every once in a while I end up doing `.write()` or `.readline()`.  There's no real reason for this not to work.

### CODE REVIEW

**Comment by zachriggle** [comment]
```py
>>> from pwn import *
>>> r = remote('google.com',80)
[*] Opening connection to google.com on port 80:
[*] Opening connection to google.com on port 80: Trying 173.194.195.113
[+] Opening connection to google.com on port 80: Done
>>> r.send('GET /\r\n\r\n')
>>> r.readline()
'HTTP/1.0 200 OK\r\n'
```

**Comment by br0ns** [comment]
I think you (or some editor macro) might have been a touch too eager; `recv_thread` is used in `interactive` i.e. it is not an API function.  Remove `read_thread` and I'll merge.

**Comment by br0ns** [comment]
Also please end the file with a NL.

**Comment by br0ns** [comment]
Oh well, did it myself :)  Merging.

**Comment by zachriggle** [comment]
Sorry not at a terminal

**Pull request merged**
